const NEW_POST_REQUEST = "NEW_POST_REQUEST";
const NEW_POST_SUCCESS = "NEW_POST_SUCCESS";
const NEW_POST_FAIL = "NEW_POST_FAIL";
const GET_MYPOST_REQUEST = "GET_MY_POST_REQUEST";
const GET_MYPOST_SUCCESS = "GET_MY_POST_SUCCESS";
const GET_MYPOST_FAIL = "GET_MY_POST_FAIL";
const GET_ALLPOST_REQUREST = "GET_ALLPOST_REQUREST";
const GET_ALLPOST_SUCCESS = "GET_ALLPOST_SUCCESS";
const GET_ALLPOST_FAIL = "GET_ALLPOST_FAIL";
const CLEAR_MESSAGES = "CLEAR_MESSAGES";
const CLEAR_ERRORS = "CLEAR_ERRORS";

export {
  NEW_POST_REQUEST,
  NEW_POST_SUCCESS,
  NEW_POST_FAIL,
  GET_MYPOST_REQUEST,
  GET_MYPOST_SUCCESS,
  GET_MYPOST_FAIL,
  GET_ALLPOST_REQUREST,
  GET_ALLPOST_SUCCESS,
  GET_ALLPOST_FAIL,
  CLEAR_ERRORS,
  CLEAR_MESSAGES,
};
