const SIGN_IN_REQUEST = "SIGN_IN_REQUEST";
const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
const SIGN_IN_FAIL = "SIGN_IN_FAIL";
const LOGIN_REQUEST = "LOGIN_REQUEST";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_FAIL = "LOGIN_FAIL";
const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
const LOAD_USER_FAIL = "LOAD_USER_FAIL";
const LOGOUT_REQUEST = "LOGOUT_REQUEST";
const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
const LOGOUT_FAIL = "LOGOUT_FAIL";
const FOLLOW_FOLLOWING_LIST_REQUEST = "FOLLOW_FOLLOWING_LIST_REQUEST";
const FOLLOW_FOLLOWING_LIST_SUCCESS = "FOLLOW_FOLLOWING_LIST_SUCCESS";
const FOLLOW_FOLLOWING_LIST_FAIL = "FOLLOW_FOLLOWING_LIST_FAIL";
const FOLLOWER_REMOVE_REQUEST = "FOLLOWER_REMOVE_REQUEST";
const FOLLOWER_REMOVE_SUCCESS = "FOLLOWER_REMOVE_SUCCESS";
const FOLLOWER_REMOVE_FAIL = "FOLLOWER_REMOVE_FAIL";
const UNFOLLOW_REQUEST = "UNFOLLOW_REQUEST";
const UNFOLLOW_SUCCESS = "UNFOLLOW_SUCCESS";
const UNFOLLOW_FAIL = "UNFOLLOW_FAIL";
const CLEAR_LIST = "CLEAR_LIST";
const CLEAR_ERRORS = "CLEAR_ERRORS";
const CLEAR_MESSAGES = "CLEAR_MESSAGES";
const POINTER_CHANGE_SUCCESS = "POINTER_CHANGE_SUCCESS";
export {
  SIGN_IN_REQUEST,
  SIGN_IN_SUCCESS,
  SIGN_IN_FAIL,
  LOGIN_REQUEST,
  LOGIN_SUCCESS,
  LOGIN_FAIL,
  LOAD_USER_REQUEST,
  LOAD_USER_SUCCESS,
  LOAD_USER_FAIL,
  LOGOUT_REQUEST,
  LOGOUT_SUCCESS,
  LOGOUT_FAIL,
  FOLLOW_FOLLOWING_LIST_REQUEST,
  FOLLOW_FOLLOWING_LIST_SUCCESS,
  FOLLOW_FOLLOWING_LIST_FAIL,
  FOLLOWER_REMOVE_REQUEST,
  FOLLOWER_REMOVE_SUCCESS,
  FOLLOWER_REMOVE_FAIL,
  UNFOLLOW_REQUEST,
  UNFOLLOW_SUCCESS,
  UNFOLLOW_FAIL,
  POINTER_CHANGE_SUCCESS,
  CLEAR_MESSAGES,
  CLEAR_ERRORS,
};
